### ISSUE TITLE
Resolving local packages works differently in playground/CLI

### ISSUE THREAD

**Issue by axoxelol1** [modmark-org/modmark#280]
Local imports like
```
[config]
import main
```
work differently in the cli and playground. The cli will look for `main.wasm` while playground looks for `main`. We should either make the playground also add the `.wasm` extension or the cli should not add it. Not sure what is best but they should be the same at least.

**Comment by CMDJojo** [comment]
Great lifting this issue! One technical note is that the name including extension is wrapped in the enum the Resolver gets to resolve.

I would say that the best way to solve this is:
* Choose an extension for our packages (we use `wasm` know, we may stick with it or move to `mmpkg` or whatever we like)
* If the string to resolve ends in `.<extension>`, keep it as-is, otherwise append it

This will behave similar to many applications which, if you want to store a file as pdf, it appends `.pdf` if absent, even if the file name already has a file extension.

We might want to add the logic for this to Core so it has more control of how stuff are being loaded, so the behaviour is easier synced. Also, worth taking into account, it will with this change be impossible to import a package with the wrong extension. I think it is fine and a reasonable thing to assert, but opinions may differ.
