### ISSUE TITLE
Playground cannot load packages in Chromium-based browsers

### ISSUE THREAD

**Issue by axoxelol1** [modmark-org/modmark#45]
**Describe the bug**
Loading packages does not work in chromium.

**To Reproduce**
1. Build and view playground in a Chromium-based browser
2. Choose HTML output or click on view packages
3. See error in console

This is currently working in firefox and webkit and should also work in chrome. Maybe not the highest priority for now but needs to be investigated.

**Screenshot**
![image](https://user-images.githubusercontent.com/40837400/218471455-e9cb7e35-6d04-4e03-9c32-222e330f631c.png)

**Comment by CMDJojo** [comment]
Do you think this may be solved by wrapping all calls to loading wasm and calling wasm-bindings in `async`/`await` in Javascript on the playground, or do you think it needs to be implemented by doing async rust? I'm thinking that wrapping everything in `async`/`await` will make it run in another JS thread, and that might be enough to stop these errors. (Of course, it is nice to do things like loading packages in parallel, but this might be a way to make it able to load the main bindgen files)

**Comment by adelhult** [comment]
Related to our issue, will take a closer look once I have time: https://github.com/wasmerio/wasmer-js/issues/314

**Comment by adelhult** [comment]
Related to our issue, will take a closer look once I have time: https://github.com/wasmerio/wasmer-js/issues/314

**Comment by adelhult** [comment]
Bug hunting update 🐛:

The reason we can't use the playground in Chromium based browsers is that when using `wasmer::Module::new` to compile WASM modules that method in itself calls the **blocking** JS `WebAssembly.Module` constructor.  And Chromium would very much prefer us to use the asynchronous JS function `WebAssembly.compile` instead.

I've played around with bypassing wasmer and using `js_sys` to call the asynchronous function instead. That could would look something like this:

```rs
async fn compile(data: &[u8]) -> js_sys::WebAssembly::Module {
	let js_bytes = unsafe { js_sys::Uint8Array::view(data) };
	let promise = js_sys::WebAssembly::compile(&js_bytes.into());
	let result = wasm_bindgen_futures::JsFuture::from(promise).await;
	result
		.unwrap()
		.dyn_into::<js_sys::WebAssembly::Module>()
		.unwrap()
}
```

And as seen in [wasmer-js](https://github.com/wasmerio/wasmer-js/blob/80b158341965d6d3203f68ae2be26d5b6858d65b/src/wasi.rs#L164) it seems like we then can convert the WebAssembly::Module into a wasmer::Module.

But, the problem is that we need to have some better way of handling asynchronous JsFuture structs in our Rust code. Sadly, as far as I understand it seems like we can't simply block inside the WASM instance that our code runs in until the module has loaded.

We should later investigate if we could make our loading of packages asynchronous by using callbacks and some kind check to see if we are still waiting for modules before we continue and evaluate our document. This might be nice for the `cli::PackageManger` to use too depending on how we implement imports too.

**Comment by CMDJojo** [comment]
> Sadly, as far as I understand it seems like we can't simply block inside the WASM instance that our code runs in until the module has loaded

When reading up on some things regarding #99, I noticed that yes, we might actually be able to block on JS Promises. It seems like wasm-bindgen generates [bindings](https://rustwasm.github.io/wasm-bindgen/reference/js-promises-and-rust-futures.html) for JS promises, which implements `std::future::Future`, so we could just block on that, but otherwise we might be able to do even better - JS has support for [worker threads](https://web.dev/workers-basics/) and this is a part of Wasm since Chrome 70+, and [web.dev](https://web.dev/webassembly-threads/#rust) even has examples on how to run stuff in other threads in Rust for Wasm (the example is using Rayon). So I do think it is possible!

**Comment by CMDJojo** [comment]
There is also a [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon) that might be useful to look at, and according to the [wasm roadmap](https://webassembly.org/roadmap/), Chrome, Firefox and Safari supports threads.

**Comment by CMDJojo** [comment]
Bingo, I think I found another way to do this, an example from rustwasm: [Wasm in web worker](https://rustwasm.github.io/wasm-bindgen/examples/wasm-in-web-worker.html) which includes a JavaScript file that loads the actual wasm file async and launches up a worker in Rust to run that JS function from that file, with promises interop and everything. I think this can be very useful. It is a complete example with all files needed to get it up and running, as far as I can see.
