### ISSUE TITLE
Rendered html output runs out of memory

### ISSUE THREAD

**Issue by axoxelol1** [modmark-org/modmark#80]
**Describe the bug**
When using the rendered html output (introduced in PR #64) the playground runs out of memory after using it for a while. Could possibly try to fix this at the same time as #45 and #78 if you were going to take a look at those two anyway @adelhult.

**To Reproduce**
Go to the website and start writing multiple modules, headings etc. I am using firefox which might be relevant.

**Screenshots**
![image](https://user-images.githubusercontent.com/40837400/220162785-e2f5dae1-0f49-4bf0-a072-b483b295926e.png)

**Comment by axoxelol1** [comment]
Hm I supposed we could. It would be nice to merge #64 to make it easier to work on new packages but I agree that it is not optimal. I could have a look and see if it is anything obvious but I'm afraid it might be hard to track down the cause.

**Comment by adelhult** [comment]
I think it might be nice to merge it anyway since we won't continue blocking people from starting writing modules.  And it only causes trouble when using the eval function and not when testing the parser.

**Comment by adelhult** [comment]
I created a first attempt at fixing the problem, but sadly I've reached a dead-end. I thought that I could solve both this and #45 by serializing and deseralizing the modules everytime they are used to avoid having a shared Engine and Store. But, sadly it seems like it's impossible to deseralizing on the web since the methods only exists and (make sense) when we have the "compiler" feature flag enabled.

This is looking quite bad, especially for #45. But I think both of the issues still can be fixed with a bit of luck.

I'll now attempt at  having a shared Engine in the Context object and new stores each time a module is invoked. The problem with this approach is that stores seem to hold a reference to the engine and I wonder if this will have any unwanted side effects. But hopefully it will work fine.
